import type { Prospect } from "./types";

export const prospects: Prospect[] = [
  {
    slug: "estilogy-sevilla",
    template: "R1",
    name: "Estilogy · Diseño y Reformas",
    shortName: "Estilogy",
    sector: "reformas",
    city: "Sevilla",
    zone: "Sevilla y alrededores",
    phone: "628 82 11 43",
    phoneHref: "+34628821143",
    website: "https://www.estilogy.es/",
    rating: "4,9★",
    reviews: "56 reseñas",
    eyebrow: "INTERIORISMO · REFORMA · DETALLE",
    hero: "Espacios que se sienten tuyos antes de terminar la obra.",
    heroAccent: "Diseño que se vive.",
    subhero: "Una propuesta editorial para que el proyecto, los acabados y la sensibilidad de la marca hablen antes que un catálogo de servicios.",
    services: ["Reforma integral", "Cocinas", "Baños", "Interiorismo"],
    trust: ["Atención personalizada", "Diseño + ejecución", "Presupuesto transparente"],
    caseTitles: ["Cocina mineral", "Baño sereno", "Vivienda abierta"],
    primaryCta: "Cuéntanos tu proyecto",
    secondaryCta: "Explorar proyectos",
    note: "Demo conceptual creada con información pública. Fotos y claims finales deben validarse con la empresa.",
  },
  {
    slug: "reformas-lago-sevilla",
    template: "R2",
    name: "Reformas Lago",
    shortName: "Lago",
    sector: "reformas",
    city: "Sevilla",
    zone: "Sevilla",
    phone: "687 03 75 73",
    phoneHref: "+34687037573",
    website: "https://reformaslago.com/",
    rating: "4,5★",
    reviews: "100+ reseñas públicas",
    experience: "35+ años",
    eyebrow: "REFORMA INTEGRAL · LLAVE EN MANO",
    hero: "Tu reforma, con el plan claro antes de empezar.",
    heroAccent: "Sin improvisar por el camino.",
    subhero: "Una web diseñada para convertir trayectoria y reputación en tranquilidad: alcance, proceso, interlocutor y siguiente paso visibles desde el primer minuto.",
    services: ["Reforma integral", "Cocinas", "Baños", "Carpintería"],
    trust: ["Planificación por fases", "Un interlocutor", "Seguimiento de obra"],
    caseTitles: ["Integral 110 m²", "Cocina llave en mano", "Actualización de vivienda"],
    primaryCta: "Valorar mi reforma",
    secondaryCta: "Ver cómo trabajamos",
    note: "Demo conceptual. Las garantías, plazos y cifras finales deben ser confirmadas por Reformas Lago.",
  },
  {
    slug: "reformas-cordoba-barata",
    template: "R3",
    name: "Reformas Córdoba Barata",
    shortName: "RCB",
    sector: "reformas",
    city: "Córdoba",
    zone: "Córdoba capital",
    phone: "857 68 28 57",
    phoneHref: "+34857682857",
    website: "https://reformasbaratascordoba.es/",
    rating: "5,0★",
    reviews: "38 reseñas",
    eyebrow: "PRESUPUESTO RÁPIDO · CÓRDOBA",
    hero: "Dinos qué quieres reformar.",
    heroAccent: "Filtramos lo importante en 60 segundos.",
    subhero: "Una demo de conversión directa: menos presentación corporativa, más intención, presupuesto y contacto útil desde móvil.",
    services: ["Reforma integral", "Baño", "Cocina", "Pintura y acabados"],
    trust: ["Solicitud guiada", "Respuesta directa", "Sin compromiso"],
    caseTitles: ["Integral", "Baño", "Cocina"],
    primaryCta: "Empezar valoración",
    secondaryCta: "Llamar ahora",
    note: "Demo de conversión. No muestra precios inventados: los rangos deben proporcionarlos la empresa.",
  },
  {
    slug: "fersan-granada",
    template: "C1",
    name: "Instalaciones FERSAN",
    shortName: "FERSAN",
    sector: "climatizacion",
    city: "La Zubia · Granada",
    zone: "Granada y área metropolitana",
    phone: "679 09 87 60",
    phoneHref: "+34679098760",
    website: "https://www.instalacionesfersan.es/",
    rating: "4,9★",
    reviews: "90+ reseñas públicas",
    eyebrow: "AEROTERMIA · CLIMATIZACIÓN · EFICIENCIA",
    hero: "Antes de elegir máquina, entendemos tu vivienda.",
    heroAccent: "Aerotermia con criterio.",
    subhero: "Una experiencia consultiva para instalaciones de alto ticket: superficie, sistema actual, emisores y objetivos antes de pedir una visita técnica.",
    services: ["Aerotermia", "Suelo radiante", "Aire acondicionado", "Fontanería"],
    trust: ["Preestudio guiado", "Solución a medida", "Instalación + puesta en marcha"],
    caseTitles: ["Vivienda unifamiliar", "Sustitución de caldera", "Climatización integral"],
    primaryCta: "Solicitar preestudio",
    secondaryCta: "Entender la aerotermia",
    note: "Demo consultiva. Certificaciones, ahorro estimado y marcas deben verificarse antes de publicar.",
  },
  {
    slug: "camino-climatizacion",
    template: "C2",
    name: "Camino Climatización",
    shortName: "Camino",
    sector: "climatizacion",
    city: "Alcalá de Guadaíra · Sevilla",
    zone: "Sevilla y alrededores",
    phone: "607 96 58 68",
    phoneHref: "+34607965868",
    rating: "5,0★",
    reviews: "valoración pública positiva",
    eyebrow: "AIRE ACONDICIONADO · RESPUESTA DIRECTA",
    hero: "¿Split, multisplit o conductos?",
    heroAccent: "Te orientamos sin marearte.",
    subhero: "Una landing pensada para móvil y para una necesidad inmediata: elegir servicio, indicar localidad y dejar un teléfono en pocos pasos.",
    services: ["Split", "Multisplit", "Conductos", "Mantenimiento"],
    trust: ["Contacto directo", "Servicio local", "Presupuesto sin compromiso"],
    caseTitles: ["Split residencial", "Multisplit", "Conductos"],
    primaryCta: "Pedir orientación",
    secondaryCta: "Llamar ahora",
    note: "No se localizó una web oficial clara durante la auditoría; los servicios finales deben confirmarse con la empresa.",
  },
  {
    slug: "aire-clima-valladolid",
    template: "C3",
    name: "Aire y Clima Valladolid S.L.",
    shortName: "Aire y Clima",
    sector: "climatizacion",
    city: "Valladolid",
    zone: "Valladolid",
    phone: "607 61 85 34",
    phoneHref: "+34607618534",
    website: "https://aireyclimavalladolid.es/",
    rating: "4,9★",
    reviews: "120+ reseñas públicas",
    experience: "40+ años de experiencia",
    eyebrow: "CLIMATIZACIÓN PROFESIONAL · INSTALACIÓN · MANTENIMIENTO",
    hero: "Capacidad técnica que también se nota antes de llamar.",
    heroAccent: "Climatización con respaldo.",
    subhero: "Una presencia B2B sobria para ordenar soluciones, experiencia, mantenimiento y credenciales sin parecer una landing residencial genérica.",
    services: ["Aire acondicionado", "Enfriadoras", "Ventilación", "Mantenimiento"],
    trust: ["Trayectoria consolidada", "Instalación profesional", "Mantenimiento técnico"],
    caseTitles: ["Retail", "Oficinas", "Residencial"],
    primaryCta: "Solicitar estudio técnico",
    secondaryCta: "Ver capacidades",
    note: "Demo B2B. Certificaciones, SLA y marcas deberán validarse con la empresa antes de producción.",
  },
];

export const prospectBySlug = (slug: string) => prospects.find((p) => p.slug === slug);
